version: "3"
services:
  gem:
    build: .
    command: bin/console
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - cassettes:/cassettes

  cassettes:
    image: drummeraki/mangadex-gem-vcr:latest
    volumes:
      - cassettes:/usr/src/app

volumes:
  cassettes:
